---
# tasks file for nginx_proxy

- name: Загрузка конфигурационного файла балансироващика
  ansible.builtin.copy:
    src: upstreams.j2
    dest: /etc/nginx/conf.d/upstreams.conf


- name: Замена конфигурационного файла default nginx
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: "Nginx Reloader"
