---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm1: #Имя машины
          ansible_host: "89.169.142.215" #Адрес машины
        vm2: #Имя машины
          ansible_host: "89.169.146.216" #Адрес машины
    proxy:
      hosts:
        vm3: #Имя машины
          ansible_host: "158.160.61.72" #Адрес машины

  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "s2367288"
    ansible__port: 22
    connection_protocol: "ssh" #тип подключения
    ansible_become: true  #Становиться ли другим пользователем после подключения
    become_method: "sudo"
    become_user: "root"
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
