--- 
- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка nginx c кастомной страницей
  hosts: nginx # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка прокисрующего сервера 
  hosts: proxy  # Будет работать на узлах в группе proxy
  roles:
    - role: nginx_proxy 
  tags:
    - nginx_proxy
