---
# tasks file for nginx_custom

#- name: Установка Nginx 
  #apt:
   # name: "nginx" 
   # state: present
- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  when: "'vm1' or 'vm2'  in inventory_hostname" # Выполнится только тогда, когда в имени есть vm1 или vm 2
  notify: "Nginx Reloader"

#- name: Проксирующий сервер
  #ansible.builtin.template:
    #name: "proxy"
    #src: upstreams.j2
    #dest: /etc/nginx/conf.d/upstreams.conf
    #src: proxy.j2
  #  #dest: /etc/nginx/sites-available/default
  #when: "'vm3' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm3
  #notify: "Nginx Reloader"

